def generate_structured_formulas():
    """Generate structured CENTRAL and Dialog search formulas"""
    
    print("=== 構造化検索式生成 - CENTRAL & Dialog形式 ===")
    print()
    
    print("📋 CENTRAL (Cochrane Library) 検索式:")
    print("=" * 80)
    print("# 構造化検索式 - CENTRAL (Cochrane Library)")
    print()
    print("## Population Block (社会的孤立・孤独感)")
    print('#1 [mh "Social Isolation"]')
    print('#2 [mh "Loneliness"]')
    print('#3 loneliness:ti,ab,kw')
    print('#4 "social isolation":ti,ab,kw')
    print('#5 "social isolat*":ti,ab,kw')
    print('#6 #1 OR #2 OR #3 OR #4 OR #5')
    print()
    print("## Intervention Block (スマートデバイス)")
    print('#7 [mh "Smartphone"]')
    print('#8 [mh "Wearable Electronic Devices"]')
    print('#9 [mh "Mobile Applications"]')
    print('#10 smartphone*:ti,ab,kw')
    print('#11 "mobile app*":ti,ab,kw')
    print('#12 "mobile application*":ti,ab,kw')
    print('#13 "wearable device*":ti,ab,kw')
    print('#14 "digital phenotyping":ti,ab,kw')
    print('#15 "passive sensing":ti,ab,kw')
    print('#16 "mobile health":ti,ab,kw')
    print('#17 mhealth:ti,ab,kw')
    print('#18 [mh "Cell Phone"]')
    print('#19 [mh "Remote Sensing Technology"]')
    print('#20 "Digital Biomarkers":ti,ab,kw')
    print('#21 "sensor data":ti,ab,kw')
    print('#22 accelerometer:ti,ab,kw')
    print('#23 "activity monitor*":ti,ab,kw')
    print('#24 app:ti,ab,kw')
    print('#25 apps:ti,ab,kw')
    print('#26 (cell:ti,ab,kw or cellular:ti,ab,kw or mobile:ti,ab,kw or smart:ti,ab,kw) AND (phone:ti,ab,kw or telephone:ti,ab,kw or device:ti,ab,kw or application:ti,ab,kw)')
    print('#27 "Handheld Computer*":ti,ab,kw')
    print('#28 "real time data":ti,ab,kw')
    print('#29 "Short Messag* Service*":ti,ab,kw')
    print('#30 SMS:ti,ab,kw')
    print('#31 "text messag*":ti,ab,kw')
    print('#32 #7 OR #8 OR #9 OR #10 OR #11 OR #12 OR #13 OR #14 OR #15 OR #16 OR #17 OR #18 OR #19 OR #20 OR #21 OR #22 OR #23 OR #24 OR #25 OR #26 OR #27 OR #28 OR #29 OR #30 OR #31')
    print()
    print("## 最終検索式")
    print('#33 #6 AND #32')
    print()
    print("=" * 80)
    print()
    
    print("📋 Dialog (Embase) 検索式:")
    print("=" * 80)
    print("# 構造化検索式 - Dialog (Embase)")
    print()
    print("## Population Block (社会的孤立・孤独感)")
    print("'social isolation'/exp")
    print("'loneliness'/exp")
    print("loneliness:ti,ab,kw")
    print("'social isolation':ti,ab,kw")
    print("'social isolat*':ti,ab,kw")
    print("1 OR 2 OR 3 OR 4 OR 5")
    print()
    print("## Intervention Block (スマートデバイス)")
    print("'smartphone'/exp")
    print("'wearable computer'/exp")
    print("'mobile application'/exp")
    print("smartphone*:ti,ab,kw")
    print("'mobile app*':ti,ab,kw")
    print("'mobile application*':ti,ab,kw")
    print("'wearable device*':ti,ab,kw")
    print("'digital phenotyping':ti,ab,kw")
    print("'passive sensing':ti,ab,kw")
    print("'mobile health':ti,ab,kw")
    print("mhealth:ti,ab,kw")
    print("'mobile phone'/exp")
    print("'remote sensing'/exp")
    print("'Digital Biomarkers':ti,ab,kw")
    print("'sensor data':ti,ab,kw")
    print("accelerometer:ti,ab,kw")
    print("'activity monitor*':ti,ab,kw")
    print("app:ti,ab,kw")
    print("apps:ti,ab,kw")
    print("(cell:ti,ab,kw OR cellular:ti,ab,kw OR mobile:ti,ab,kw OR smart:ti,ab,kw) AND (phone:ti,ab,kw OR telephone:ti,ab,kw OR device:ti,ab,kw OR application:ti,ab,kw)")
    print("'Handheld Computer*':ti,ab,kw")
    print("'real time data':ti,ab,kw")
    print("'Short Messag* Service*':ti,ab,kw")
    print("SMS:ti,ab,kw")
    print("'text messag*':ti,ab,kw")
    print("7 OR 8 OR 9 OR 10 OR 11 OR 12 OR 13 OR 14 OR 15 OR 16 OR 17 OR 18 OR 19 OR 20 OR 21 OR 22 OR 23 OR 24 OR 25 OR 26 OR 27 OR 28 OR 29 OR 30 OR 31")
    print()
    print("## 最終検索式")
    print("6 AND 32")
    print()
    print("=" * 80)
    print()
    
    print("✅ 構造化検索式生成完了!")
    print()
    print("📊 検索式統計:")
    print("- Population Block: 6行 (Social Isolation, Loneliness関連)")
    print("- Intervention Block: 26行 (スマートデバイス関連)")
    print("- 最終検索式: 1行 (Population AND Intervention)")
    print("- 総行数: 33行")
    print()
    print("🎯 使用方法:")
    print("1. CENTRAL: Cochrane Libraryで#1から#33まで順次実行")
    print("2. Dialog: Embaseで1から33まで順次実行（番号プレフィックスなし）")
    print("3. 各データベースの最新シンタックスを事前確認してください")
    
    return True

if __name__ == "__main__":
    generate_structured_formulas()
    print(f"\n🎉 生成完了: CENTRAL & Dialog構造化検索式")
